#!/usr/bin/env bash

if [[ -x ".ready-tmux" ]]; then
	./.ready-tmux
elif [[ -x "$HOME/.ready-tmux" ]]; then
	$HOME/.ready-tmux
else
    echo "No executable ready-tmux script found in HOME or local directory."
    exit 0
fi
clear
