#!/usr/bin/env bash

selected=$(find ~/personal -mindepth 1 -maxdepth 1 -type d | fzf)
if [[ -z "$selected" ]]; then
    exit 0
fi

selected_name=$(basename $selected | tr ":,. " "____")

switch_to() {
	if [[ -z "$TMUX" ]]; then
		tmux attach-session -t $selected_name
	else
		tmux switch-client -t $selected_name
	fi
}

if tmux has-session -t=$selected_name 2> /dev/null; then
	switch_to
	exit 0
fi

tmux new-session -ds $selected_name -c $selected

timeout=10
start_time=$SECONDS
while ! tmux has-session -t="$selected_name" 2>/dev/null; do
    totalTime=$(SECONDS - start_time)

  if (( SECONDS - start_time >= timeout )); then
    echo "Timeout reached while waiting for tmux session '$selected_name'. Exiting."
    exit 1  # or return, depending on your use case
  fi
  echo "slept total of $totalTime"
  sleep 0.05
done

tmux send-keys -t $selected_name "ready-tmux" ^M
sleep 0.25
switch_to

